USE registrar_db_v2;

-- ============================================================
-- TOOL SCRIPTS & PROCEDURES
-- Project: EIR Registrar System - Scholarship Module Phase 2
-- Dialect: MySQL
-- Note: Utility actions for adding applicants, clearing test data,
-- and manually granting scholarships inside the legacy frame.
-- ============================================================

-- ------------------------------------------------------------
-- 1. MACRO: Delete All Test Students & Reset
-- Safely scrubs only the dummy students generated by the Mega Script
-- without touching your real historical data.
-- ------------------------------------------------------------
DELIMITER $$
DROP PROCEDURE IF EXISTS reset_all_test_data$$
CREATE PROCEDURE reset_all_test_data()
BEGIN
    SET FOREIGN_KEY_CHECKS = 0;
    
    -- Scrub the applicant side
    DELETE FROM eac_applicants WHERE ref_no LIKE 'REF-00%';
    
    -- Scrub the Jaypee Engine (Cascades will fail without FK disabled sometimes depending on schema, so we do it manual safely)
    DELETE FROM jp_grades WHERE student_id IN (SELECT id FROM jp_students WHERE first_name LIKE 'TestStudent_%');
    DELETE FROM jp_student_enlistments WHERE student_id IN (SELECT id FROM jp_students WHERE first_name LIKE 'TestStudent_%');
    DELETE FROM jp_students WHERE first_name LIKE 'TestStudent_%';
    
    -- Scrub the main sys_users table
    DELETE FROM student_scholarships WHERE user_id IN (SELECT user_id FROM sys_users WHERE username LIKE '2026-T%');
    DELETE FROM sys_users WHERE username LIKE '2026-T%';
    
    -- Quick reset of all scholarships if needed
    -- DELETE FROM student_scholarships; 
    
    SET FOREIGN_KEY_CHECKS = 1;
END $$
DELIMITER ;

-- ------------------------------------------------------------
-- 2. MACRO: Fast Add Applicant
-- ------------------------------------------------------------
DELIMITER $$
DROP PROCEDURE IF EXISTS add_quick_applicant$$
CREATE PROCEDURE add_quick_applicant(
    IN p_ref_no VARCHAR(30), 
    IN p_first VARCHAR(100), 
    IN p_last VARCHAR(100)
)
BEGIN
    INSERT INTO eac_applicants (ref_no, first_name, last_name, applicant_status) 
    VALUES (p_ref_no, p_first, p_last, 'SUBMITTED');
END $$
DELIMITER ;

-- ------------------------------------------------------------
-- 3. MACRO: Grant Manual External Scholarship
-- Checks against `sys_users` to ensure the student has an ID.
-- ------------------------------------------------------------
DELIMITER $$
DROP PROCEDURE IF EXISTS grant_manual_scholarship$$
CREATE PROCEDURE grant_manual_scholarship(
    IN p_sys_user_id INT, 
    IN p_classification VARCHAR(50), 
    IN p_semester INT
)
BEGIN
    DECLARE v_username VARCHAR(50);
    DECLARE v_type_id INT;
    DECLARE v_requires_id TINYINT(1);
    
    -- Validate Student ID prerequisite
    SELECT username INTO v_username FROM sys_users WHERE user_id = p_sys_user_id;
    
    -- Get Type ID
    SELECT type_id, requires_id INTO v_type_id, v_requires_id 
    FROM scholarship_types WHERE classification = p_classification LIMIT 1;
    
    IF v_requires_id = 1 AND (v_username IS NULL OR v_username = '') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR: Manual scholarship requires an officially generated Student ID.';
    ELSE
        INSERT INTO student_scholarships (user_id, type_id, semester_id, status) 
        VALUES (p_sys_user_id, v_type_id, p_semester, 'ACTIVE');
    END IF;
END $$
DELIMITER ;

-- ------------------------------------------------------------
-- 4. MACRO: Revoke Scholarship
-- ------------------------------------------------------------
DELIMITER $$
DROP PROCEDURE IF EXISTS revoke_scholarship$$
CREATE PROCEDURE revoke_scholarship(IN p_scholarship_id INT)
BEGIN
    UPDATE student_scholarships SET status = 'REVOKED' WHERE scholarship_id = p_scholarship_id;
END $$
DELIMITER ;
