-- =============================================================================
-- BSIT curriculum + term polish — RUN ORDER (execute each file separately)
--
-- 1. 00_upsert_academic_terms_calendar.sql
-- 2. 00_seed_bsit_curriculum_set_official.sql
-- 3. 01_seed_bsit_class_sections_demo.sql
-- 4. (optional) 02_cleanup_legacy_bscit_courses.sql
-- 5. (optional) capss-demo-required/01_setup/03_seed_program_fees_full_lifecycle.sql
--
-- After step 3, set enrollment open term in system_settings, e.g.:
--   UPDATE system_settings SET setting_value = 'SL_2120242025'
--   WHERE setting_key = 'CURRENT_ACADEMIC_TERM';
-- (Y1 S2, A.Y. 2024-2025 2nd Semester — or use DB code 2120242025)
--
-- Set student term_year to match (sys_users / students), e.g. SL_2120242025 for Y1 S2.
-- =============================================================================
