DROP TABLE IF EXISTS registrar_sandbox.sys_users;
CREATE TABLE registrar_sandbox.sys_users (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `real_name` varchar(100) DEFAULT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `middle_name` varchar(100) DEFAULT NULL,
  `role` varchar(30) DEFAULT NULL,
  `program_code` varchar(100) DEFAULT NULL,
  `year_level` int(11) DEFAULT 1,
  `semester` int(11) DEFAULT 1,
  `term_year` varchar(30) DEFAULT 'SL_1120252026',
  `reference_number` varchar(50) DEFAULT NULL,
  `student_type` varchar(50) DEFAULT NULL,
  `enrollment_status_type` varchar(50) DEFAULT NULL,
  `scholarship_type` varchar(50) DEFAULT 'NONE',
  `discount_percentage` decimal(5,2) DEFAULT 0.00,
  `admission_status` varchar(50) DEFAULT NULL,
  `admission_date` datetime DEFAULT NULL,
  `enrollment_blocked` tinyint(1) DEFAULT 0,
  `enrollment_start_time` datetime DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `street` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `last_school` varchar(200) DEFAULT NULL,
  `course_taken` varchar(200) DEFAULT NULL,
  `form138_path` varchar(255) DEFAULT NULL,
  `good_moral_path` varchar(255) DEFAULT NULL,
  `psa_birth_cert_path` varchar(255) DEFAULT NULL,
  `id_picture_path` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `status` varchar(30) DEFAULT 'ACTIVE',
  `granted_permissions` text DEFAULT NULL,
  `scholarship_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `scholarship_approved` tinyint(1) NOT NULL DEFAULT 0,
  `section_group` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT IGNORE INTO registrar_sandbox.sys_users (username, password, role, is_active) VALUES ('admin', '$2a$10$ScZZ4sR0O0CGegp4whjIBurHtZQdBXYznaRqE99UQtNgDbLqWS2Wm', 'Admin', 1);
